# Generated by Django 3.2 on 2023-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='zone',
        ),
        migrations.AddField(
            model_name='campaign',
            name='zone',
            field=models.ManyToManyField(to='mstreets.Zone'),
        ),
    ]
