# Generated by Django 3.2 on 2023-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0004_auto_20230220_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='has_mini',
            field=models.BooleanField(default=False, verbose_name='Hi ha imatge reduida'),
        ),
    ]
