# Generated by Django 3.2 on 2023-07-20 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0007_alter_zone_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Permís territorial', 'verbose_name_plural': '     Permisos territorials'},
        ),
        migrations.AddField(
            model_name='zone',
            name='pc_permission',
            field=models.BooleanField(default=True, help_text='Accés als núvols de punts de la zona', verbose_name='Permisos PC'),
        ),
        migrations.AddField(
            model_name='zone',
            name='poi_permission',
            field=models.BooleanField(default=True, help_text="Accés als punts d'interès (panorames, etc) de la zona", verbose_name='Permisos POI'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Perímetre campanya'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripció de la zona'),
        ),
    ]
