# Generated by Django 3.2 on 2023-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0008_auto_20230720_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='pc_permission',
            field=models.BooleanField(default=True, help_text='Pot veure els núvols de punts de la zona', verbose_name='Pot veure PC'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='poi_permission',
            field=models.BooleanField(default=True, help_text="Pot veure els punts d'interès (panorames, laterals, etc) de la zona", verbose_name='Pot veure POI'),
        ),
    ]
