# Generated by Django 3.2 on 2025-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0016_campaign_epsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sync_pano',
            field=models.BooleanField(default=True, verbose_name='Es poden sincronitzar els panorames amb els núvols de punts'),
        ),
    ]
