# Generated by Django 3.2 on 2025-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0017_campaign_sync_pano'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='angle_height',
            field=models.FloatField(blank=True, help_text='Alçada amb graus que ocupa el panorama', null=True, verbose_name="Alçada de l'angle"),
        ),
        migrations.AddField(
            model_name='poi',
            name='angle_height_offset',
            field=models.FloatField(blank=True, null=True, verbose_name="Desplaçament vertical de l'angle"),
        ),
        migrations.AddField(
            model_name='poi',
            name='angle_width',
            field=models.FloatField(blank=True, help_text='Amplada amb graus que ocupa el panorama', null=True, verbose_name="Amplada de l'angle"),
        ),
    ]
