# Generated by Django 3.2 on 2025-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0018_auto_20250523_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='angle_height',
            field=models.FloatField(blank=True, help_text='Alçada amb graus que ocupa el panorama (només cal si la imatge no és de 360º)', null=True, verbose_name="Alçada de l'angle"),
        ),
        migrations.AlterField(
            model_name='poi',
            name='angle_width',
            field=models.FloatField(blank=True, help_text='Amplada amb graus que ocupa el panorama (només cal si la imatge no és de 360º)', null=True, verbose_name="Amplada de l'angle"),
        ),
    ]
