# Generated by Django 3.2.17 on 2025-10-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstreets', '0019_auto_20250523_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='context_info_api',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Context Info API'),
        ),
    ]
