import os
from django.conf import settings

PANORAMAS_ROOT = os.environ.get(
    'PANORAMAS_ROOT', os.path.join(settings.MEDIA_ROOT, 'panoramas')).rstrip('/')

PANORAMAS_BUCKET_NAME = os.environ.get('PANORAMAS_BUCKET_NAME', '')
PANORAMAS_BUCKET_REGION = os.environ.get('PANORAMAS_BUCKET_REGION', '')
PANORAMAS_BUCKET_ACCESS_KEY = os.environ.get('PANORAMAS_BUCKET_ACCESS_KEY', '')
PANORAMAS_BUCKET_SECRET_KEY = os.environ.get('PANORAMAS_BUCKET_SECRET_KEY', '')

AWS_STORAGE_BUCKET_NAME = PANORAMAS_BUCKET_NAME
AWS_S3_REGION_NAME = PANORAMAS_BUCKET_REGION
AWS_S3_ENDPOINT_URL = f'https://{PANORAMAS_BUCKET_REGION}.linodeobjects.com'
AWS_ACCESS_KEY_ID = PANORAMAS_BUCKET_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = PANORAMAS_BUCKET_SECRET_KEY
